#!/bin/sh
# attribution-gate.sh: a commit, a tag, an MR description or a progress file may not carry a co-author
# trailer, a session line or URL, a "generated with" line or the robot emoji; every other call passes.
# Since MR !414 (2026-09-22) the gate also resolves the files a publishing command reads, so the escape that
# incident took - a body written to a scratch file and handed to `glab mr update` through `$(cat ...)` - is a
# case here, next to every other file-carried route and the wider phrase list.
set -u
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
fail=0
tmp=$(mktemp -d "$root/.attribution-gate-test.XXXXXX") || exit 1
trap 'rm -rf "$tmp"' EXIT INT TERM
mkdir -p "$tmp/scratchpad"

footer='**What changed** - the gate resolves body files

'"$(printf '\360\237\244\226')"' Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01TnAbLKAmSYz4T3rK9z9pST
'
printf '%s' "$footer" > "$tmp/mr414.md"
printf '%s' 'fix(gate): scan the body file

Co-Authored-By: Claude <noreply@anthropic.com>
' > "$tmp/msg.txt"
printf '%s' '**What changed** - the bullet collector joins wrapped lines
**Why** - a wrapped bullet was cut in half
**How to verify** - sh tests/attribution-gate.test.sh
' > "$tmp/clean.md"

try() { # <want exit> <label> <json payload>
  printf '%s' "$3" | sh "$root/bin/attribution-gate.sh" >/dev/null 2>&1
  got=$?
  if [ "$got" -eq "$1" ]; then printf 'PASS %s\n' "$2"; else printf 'FAIL want=%s got=%s %s\n' "$1" "$got" "$2"; fail=1; fi
}
bash_payload() {
  node -e 'process.stdout.write(JSON.stringify({tool_name:"Bash",cwd:process.argv[1],tool_input:{command:process.argv[2]}}))' \
    "$root" "$1"
}
write_payload() {
  node -e 'process.stdout.write(JSON.stringify({tool_name:"Write",cwd:process.argv[1],tool_input:{file_path:process.argv[2],content:process.argv[3]}}))' \
    "$root" "$1" "$2"
}

try 2 'a co-author trailer on a commit' "$(bash_payload 'git commit -m "feat: x

Co-Authored-By: Claude <noreply@anthropic.com>"')"
try 2 'a session line on a commit'      "$(bash_payload 'git commit -m "feat: x

Claude-Session: https://claude.ai/code/session_1"')"
try 2 'an attributed MR description'    "$(write_payload '/w/acme/T-001/.harness/T-001/mr.md' '**What changed** - x

Generated with [Claude Code]
')"

# the MR !414 route and its siblings: the text is in a file the command reads
try 2 'a body through $(cat file)'      "$(bash_payload "glab mr update 414 --description \"\$(cat $tmp/mr414.md)\"")"
try 2 'glab mr create --description-file' \
  "$(bash_payload "glab mr create --source-branch x --target-branch main --title \"fix(gate): y\" --description-file $tmp/mr414.md --yes")"
try 2 'gh pr create --body-file'        "$(bash_payload "gh pr create --base main --title \"fix(gate): y\" --body-file $tmp/mr414.md")"
try 2 'gh pr edit --body-file'          "$(bash_payload "gh pr edit 5 --body-file $tmp/mr414.md")"
try 2 'glab api -f description=@file'   "$(bash_payload "glab api -X PUT projects/1/merge_requests/414 -f description=@$tmp/mr414.md")"
try 2 'git commit -F file'              "$(bash_payload "git commit -F $tmp/msg.txt")"

# the option forms that broke the old substring match
try 2 'git -C dir commit'               "$(bash_payload 'git -C /some/dir commit -m "x

Co-Authored-By: Claude <noreply@anthropic.com>"')"
try 2 'a push option carrying a body'   "$(bash_payload "git push -o merge_request.create -o merge_request.description=\"$(printf '\360\237\244\226') Generated with Claude Code\"")"
try 2 'a phrase variant on a commit'    "$(bash_payload 'git commit -m "docs: x

Generated by Claude Code"')"

# the write side beyond the four original globs
try 2 'a scratchpad MR body'            "$(write_payload "$tmp/scratchpad/mr414.md" "$footer")"
try 2 'an MR body under any name'       "$(write_payload "$tmp/notes.md" "$footer")"

# the name patterns match claude and ai as whole words, not "ai" inside email or maintainers
printf '%s' 'The export was created by the nightly job and reported in an email from support.
' > "$tmp/issue.md"
try 0 'an issue body with created by and email' \
  "$(bash_payload "gh issue create --title \"fix: export fails\" --body-file $tmp/issue.md")"
try 0 'a commit with written by and maintainers' "$(bash_payload 'git commit -m "docs: notes written by the maintainers"')"
try 2 'made with claude'                "$(bash_payload 'git commit -m "docs: x

made with claude"')"
try 2 'created by ai'                   "$(bash_payload 'git commit -m "docs: x

created by ai"')"
try 2 'written by the claude model'     "$(bash_payload 'git commit -m "docs: x

written by the claude model."')"

# bin/issue-create.sh publishes an issue: its --body-file is read and its --title is scanned in the command text,
# and the ai-drafted label it adds is the one sanctioned marker, not an attribution line
try 2 'issue-create.sh with a co-author trailer in the body file' \
  "$(bash_payload "sh bin/issue-create.sh k --title \"fix: export fails\" --body-file $tmp/msg.txt")"
try 2 'issue-create.sh by its plugin path with a footer in the body file' \
  "$(bash_payload "\"/home/u/.claude/plugins/cache/claude-factory/claude-factory/0.14.4/bin/issue-create.sh\" k --title \"fix: export fails\" --body-file $tmp/mr414.md")"
try 2 'issue-create.sh with an attributed title' \
  "$(bash_payload "sh bin/issue-create.sh k --title \"export fails, made with claude\" --body-file $tmp/issue.md")"
try 0 'issue-create.sh with a clean body file' \
  "$(bash_payload "sh bin/issue-create.sh k --title \"fix: export fails\" --body-file $tmp/issue.md")"
try 0 'gh issue create with the ai-drafted label and a clean body' \
  "$(bash_payload "gh issue create -R github.com/acme/widgets --title \"fix: export fails\" --body-file $tmp/issue.md --label ai-drafted")"
# the label name after a phrase verb is no name pattern hit: ai is followed by a hyphen, not a word end
printf '%s' 'This issue was created with the ai-drafted label by bin/issue-create.sh.
' > "$tmp/labelled.md"
try 0 'an issue body naming the ai-drafted label after created with' \
  "$(bash_payload "gh issue create -R github.com/acme/widgets --title \"fix: export fails\" --body-file $tmp/labelled.md --label ai-drafted")"
# only the exact label name is exempt: every other hyphenated claude or ai name after a phrase verb is denied
body_try() { # <label> <body line>
  printf '%s\n' "$2" > "$tmp/named.md"
  try 2 "$1" "$(bash_payload "gh issue create -R github.com/acme/widgets --title \"fix: export fails\" --body-file $tmp/named.md --label ai-drafted")"
}
body_try 'an issue body with created with then claude-code' 'This issue was created with claude-code today.'
body_try 'an issue body with written by then ai-assistance' 'This issue was written by ai-assistance today.'
body_try 'an issue body line ending in the bare name' 'This issue was created by claude'
body_try 'an issue body with the bare name and a full stop' 'This issue was created by claude.'

try 0 'a clean description file'        "$(bash_payload "glab mr create --source-branch x --target-branch main --title \"fix(gate): y\" --description-file $tmp/clean.md --yes")"
try 0 'a plain commit'                  "$(bash_payload 'git commit -m "feat(api): add the feed endpoint"')"
try 0 'a regenerated lockfile'          "$(bash_payload 'git commit -m "chore: lockfile regenerated by npm ci"')"
try 0 'a docs commit naming the product' "$(bash_payload 'git commit -m "docs: mention the claude-code marketplace"')"
try 0 'a plain fix commit'              "$(bash_payload 'git commit -m "fix: plain"')"
try 0 'an unrelated command'            "$(bash_payload 'ls')"
try 0 'an unrelated command with flags' "$(bash_payload 'ls -la')"
try 0 'a source file'                   "$(write_payload '/w/acme/T-001/src/A.cs' 'public class A { }')"
try 0 'a source file naming a trailer'  "$(write_payload "$tmp/Trailer.cs" 'const string T = "Co-authored-by: someone";')"
exit $fail
